### ISSUE TITLE
Display extrinsic meta documentation on hover

### ISSUE THREAD

**Issue by jacogr** [polkadot-js/apps#969]
Goal:

To make specific extrinsic information available at the fingertips of the user, as opposed to referencing more external documentation.

Background:

Currently the metadata returns in-code documentation that expands on the methods for both the extrinsics and chain state. This information is used to display a very condensed summary in the extrinsic selection, i.e.

![image](https://user-images.githubusercontent.com/1424473/55962260-d15aeb80-5c70-11e9-8588-dc1a6ae522c4.png)

We wish to expand this to actually show all information.

Actions:

- Expand the `submit the following extrinsic` label (or any label passed for an Extrinsic/Proposal to contain `help` with the actual documentation.
- As the method selection changes, the updated documentation becomes available as part of the hover. (This is actually better suited to the dropdown itself, and _may_ work as a tooltip - but these things are large)

Bonus:

Also apply to the chain state app

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__This issue now has a funding of 150.0 DAI (150.0 USD @ $1.0/DAI)  attached to it as part of the W3F fund.__

 * If you would like to work on this issue you can 'start work' [on the Gitcoin Issue Details page](https://gitcoin.co/issue/polkadot-js/apps/969/2934).
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/polkadot-js/apps/969/2934).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $94,655.87 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. **Open** 2. Started 3. Submitted 4. Done 

<hr>

__Workers have applied to start work__.


These users each claimed they can complete the work by 12 months from now.
Please review their action plans below:


**1) [sebastiancaso](https://gitcoin.co/profile/sebastiancaso) has applied to start work _(Funders only: [approve worker](https://gitcoin.co/issue/polkadot-js/apps/969/2934?mutate_worker_action=approve&worker=sebastiancaso) | [reject worker](https://gitcoin.co/issue/polkadot-js/apps/969/2934?mutate_worker_action=reject&worker=sebastiancaso))_.**

No questions on the ticket, seems pretty straightforward.  I'll review the code then come up with the best solution possible.

Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/polkadot-js/apps/969/2934).

**Comment by gitcoinbot** [comment]
@georgiemathews Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=1) | [3 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=3) | [5 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=5) | [10 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=10) | [100 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=100)

**Comment by pbteja1998** [comment]
@jacogr Is this available?  If so, I want to give this a try.

**Comment by jacogr** [comment]
@pbteja1998 It has been assigned as of now, however if the status does change, it should reflect here via the Gitcoin updates.

**Comment by gitcoinbot** [comment]
@georgiemathews Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=1) | [3 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=3) | [5 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=5) | [10 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=10) | [100 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=100)

**Comment by georgiemathews** [comment]
@gitcoinbot still working, should be done in the next two days!

**Comment by gitcoinbot** [comment]
@georgiemathews Hello from Gitcoin Core - are you still working on this issue? Please submit a WIP PR or comment back within the next 3 days or you will be removed from this ticket and it will be returned to an ‘Open’ status. Please let us know if you have questions!
* [x] reminder (3 days)
* [ ] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=1) | [3 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=3) | [5 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=5) | [10 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=10) | [100 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=100)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. **Started** 3. Submitted 4. Done 

<hr>

@georgiemathews due to inactivity, we have escalated [this issue](https://gitcoin.co/issue/polkadot-js/apps/969/2934) to Gitcoin's moderation team. Let us know if you believe this has been done in error!

* [x] reminder (3 days)
* [x] escalation to mods (6 days)

Funders only: Snooze warnings for [1 day](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=1) | [3 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=3) | [5 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=5) | [10 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=10) | [100 days](https://gitcoin.co/issue/polkadot-js/apps/969/2934?snooze=100)

**Comment by Web3Foundation** [comment]
Hey @georgiemathews just checking in on you. Is this bounty still a WIP for you?

**Comment by pbteja1998** [comment]
@jacogr I think this bounty's status returned to `open`. Can I take this?

**Comment by jacogr** [comment]
@pbteja1998 Yes, please. You can just apply via gitcoin

**Comment by pbteja1998** [comment]
@jacogr I have applied through gitcoin. Before I start, I have a few doubts.

- You want to show more information about all the `labels` in the form...  like rendering a "?" symbol next to each label, which acts similar to a `tootltip`. Is this what is required?

**Comment by pbteja1998** [comment]
Also, in `bonus` section, you wrote `Also apply to chain state app`. What do u mean by this? Is this another repo?

**Comment by Tbaut** [comment]
> Also, in `bonus` section, you wrote `Also apply to chain state app`. What do u mean by this? Is this another repo?

What is meant here is: we can apply the same changes to another app, it is another section in the UI called "Chain state", it's in the same repo, just a different package: https://github.com/polkadot-js/apps/tree/master/packages/app-storage

I let Jaco answer the first question.

**Comment by jacogr** [comment]
@pbteja1998 So yes, if you look at the app, we already have that available everywhere we use labels (not in extrinics and not in state), i.e.

![image](https://user-images.githubusercontent.com/1424473/58569272-15f91100-8236-11e9-9573-12af841d770c.png)

So the label wrapper already take and (optional) help prop, that handles the rendering. So on extrinsics, when we swap the section/method, we just need to dynamically determine what the metadata is (it already gets rendered in the method dropdown) and then pass that to the `help` prop.

Dos this make sense?

**Comment by pbteja1998** [comment]
On what basis should I determine the meta data for a `label`?

**Comment by jacogr** [comment]
The metadata is return from the chain. So each call has documentation. So currently when constructing the dropdowns, these are attached and appear (in summary form), inside the item, i.e.

![image](https://user-images.githubusercontent.com/1424473/58571772-b8b38e80-823a-11e9-9970-e02f9578950b.png)
 
This is extracted from the methods itself (as an example), here -

https://github.com/polkadot-js/apps/blob/master/packages/ui-app/src/InputExtrinsic/options/method.tsx#L41

So the same logic would apply in the `onChange` event of the extrinsic selection, i.e. here https://github.com/polkadot-js/apps/blob/master/packages/app-extrinsics/src/Selection.tsx#L125

Since an extrinsic gets passed, you can inspect it in the same way as above and then just attache the documentation as the help.

The same (from extrinsic) takes place when submitting - 

![image](https://user-images.githubusercontent.com/1424473/58571963-1cd65280-823b-11e9-97b6-4627aa118439.png)

i.e. here is an actual complete example as to how to extract from the actual extrinsic,

https://github.com/polkadot-js/apps/blob/master/packages/ui-signer/src/Transaction.tsx#L29-L40

**Comment by pbteja1998** [comment]
@jacogr Thanks for the detailed explanation. Can you please approve me in `gitcoin`. I will start working on this immediately.

**Comment by Web3Foundation** [comment]
@pbteja1998 approved.

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. **Submitted** 4. Done 

<hr>

__Work for 150.0 DAI (150.0 USD @ $1.0/DAI) has been submitted by__:

 1. [@pbteja1998](https://gitcoin.co/profile/pbteja1998)



@Web3Foundation please take a look at the submitted work:
* [PR](https://github.com/polkadot-js/apps/pull/1247) by @pbteja1998

<hr>

* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/polkadot-js/apps/969/2934)
* Want to chip in? Add your own contribution [here](https://gitcoin.co/issue/polkadot-js/apps/969/2934).
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $69,046.25 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)

**Comment by gitcoinbot** [comment]
Issue Status: 1. Open 2. Started 3. Submitted 4. **Done** 

<hr>

__The funding of 150.0 DAI (150.0 USD @ $1.0/DAI)  attached to this issue has been approved & issued to @pbteja1998.__  

 
* Learn more [on the Gitcoin Issue Details page](https://gitcoin.co/issue/polkadot-js/apps/969/2934)
* Questions? Checkout <a href='https://gitcoin.co/help'>Gitcoin Help</a> or the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
* $69,096.25 more funded OSS Work available on the [Gitcoin Issue Explorer](https://gitcoin.co/explorer)
